---
- name: Initialize swarm cluster
  shell: docker swarm init --advertise-addr={{ swarm_iface | default('eth0') }}:2377
  when:
    - "'swarm_manager_operational' not in groups"
    - "'swarm_manager_bootstrap' in group_names"
  register: bootstrap_first_node

- name: Add initialized host to swarm_manager_operational group
  add_host:
    hostname: "{{ inventory_hostname }}"
    groups: swarm_manager_operational
  when: bootstrap_first_node is changed
